/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import control.ControllerView;
import control.UtilGeral;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author joaop
 */
public class DlgListaConsulta extends javax.swing.JDialog {
    private ControllerView gerIG;
    /**
     * Creates new form DlgAgendamentos
     */
    public DlgListaConsulta(java.awt.Frame parent, boolean modal, ControllerView controller) {
        super(parent, modal);
        initComponents();
        gerIG = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        cadastrar = new javax.swing.JMenuItem();
        excluir = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenuItem();
        jpTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultas = new javax.swing.JTable();
        btRelatorio = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        lbPesquisar = new javax.swing.JLabel();
        txtPesquisaData = new javax.swing.JFormattedTextField();
        btLupa = new javax.swing.JButton();
        btListarTodas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        cadastrar.setText("Inserir");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        popMenu.add(cadastrar);

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        popMenu.add(excluir);

        relatorio.setText("Excluir");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });
        popMenu.add(relatorio);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Consultas");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(86, 106, 107));
        jpTitulo.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Consultas");
        jpTitulo.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 599, 72));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA", "HORÁRIO", "MÉDICO", "PACIENTE", "FUNCIONÁRIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbConsultas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, 581, 180));

        btRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/relatorio 24x24.png"))); // NOI18N
        btRelatorio.setText("Relatório");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });
        jPanel1.add(btRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 130, 35));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/lixera 24x24.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 35));

        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/adicionar 24x24.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 35));

        lbPesquisar.setText("Pesquisar por data.:");
        jPanel1.add(lbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, -1));

        try {
            txtPesquisaData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtPesquisaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 11, 89, 34));

        btLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/lupa24-icon.png"))); // NOI18N
        btLupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLupaActionPerformed(evt);
            }
        });
        jPanel1.add(btLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 11, -1, 34));

        btListarTodas.setText("LISTAR TODAS");
        btListarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarTodasActionPerformed(evt);
            }
        });
        jPanel1.add(btListarTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 11, -1, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, -1, 308));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/Tela600X466.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos(){
        lbPesquisar.setForeground(Color.black);
        String msgErro = "";
        boolean data = UtilGeral.verificarFormatoData(txtPesquisaData.getText());
        if(data == false){
            lbPesquisar.setForeground(Color.red);
            msgErro += "data inválida\n";
        }
        
        if(msgErro.isEmpty()){
            return true;
        }else{
            JOptionPane.showMessageDialog(this, msgErro, "Verifique os campos e tente novamente", JOptionPane.ERROR_MESSAGE);
            return false; 
        }
                
    }
    
    private void btListarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarTodasActionPerformed
        //busca as consultas no banco e insere na tabela
    }//GEN-LAST:event_btListarTodasActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        gerIG.janelaCadConsulta();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLupaActionPerformed
        if (validarCampos()) {
            //faz a busca no banco e lista pela data
        }
        lbPesquisar.setForeground(Color.black);
    }//GEN-LAST:event_btLupaActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int opcao = tbConsultas.getSelectedRow();
        if(opcao >= 0){
            // excluir do banco
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha!");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        int linha = tbConsultas.getSelectedRow();
        if(linha >= 0){
            
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRelatorioActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListarTodas;
    private javax.swing.JButton btLupa;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JMenuItem cadastrar;
    private javax.swing.JMenuItem excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JLabel lbPesquisar;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JMenuItem relatorio;
    private javax.swing.JTable tbConsultas;
    private javax.swing.JFormattedTextField txtPesquisaData;
    // End of variables declaration//GEN-END:variables
}
