/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import control.ControllerView;

/**
 *
 * @author joaop
 */
public class FrmMenu extends javax.swing.JFrame {
    private ControllerView gerIG;

    
    public FrmMenu(ControllerView controller) {
        initComponents(); 
        gerIG = controller;
        rbtnClaro.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTema = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jpBotoes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btConsultas = new javax.swing.JButton();
        btPacientes = new javax.swing.JButton();
        btMedicos = new javax.swing.JButton();
        btFuncionarios = new javax.swing.JButton();
        btServicos = new javax.swing.JButton();
        btRelatorios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmiCadastrarPaciente = new javax.swing.JMenuItem();
        jmiCadastrarMedico = new javax.swing.JMenuItem();
        jmiCadastrarFuncionario = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiAgendarConsultas = new javax.swing.JMenuItem();
        jmiListarConsultas = new javax.swing.JMenuItem();
        jmiRemarcarEditarConsultas = new javax.swing.JMenuItem();
        jmRelatórios = new javax.swing.JMenu();
        jmiRelatorioConsultas = new javax.swing.JMenuItem();
        jmiRelatorioPacientes = new javax.swing.JMenuItem();
        jmiRelatorioMedicos = new javax.swing.JMenuItem();
        jmiRelatorioFuncionarios = new javax.swing.JMenuItem();
        jmConfiguracoes = new javax.swing.JMenu();
        jmTema = new javax.swing.JMenu();
        rbtnClaro = new javax.swing.JRadioButtonMenuItem();
        rbtnEscuro = new javax.swing.JRadioButtonMenuItem();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GERENCIADOR DE CONSULTAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 660, 56));

        jpBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jpBotoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpBotoes.setOpaque(false);

        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 70, 70));
        jPanel1.setOpaque(false);

        btConsultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/consulta 01 - 32.png"))); // NOI18N
        btConsultas.setMnemonic('c');
        btConsultas.setText("Consultas");
        btConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btConsultas);

        btPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/cliente 01 - 32.png"))); // NOI18N
        btPacientes.setMnemonic('p');
        btPacientes.setText("Pacientes");
        btPacientes.setPreferredSize(new java.awt.Dimension(129, 41));
        btPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(btPacientes);

        btMedicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/Medico 1 - 32.png"))); // NOI18N
        btMedicos.setMnemonic('m');
        btMedicos.setText("Médico");
        btMedicos.setPreferredSize(new java.awt.Dimension(129, 41));
        btMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedicosActionPerformed(evt);
            }
        });
        jPanel1.add(btMedicos);

        btFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/Funcionario 01 - 32.png"))); // NOI18N
        btFuncionarios.setMnemonic('f');
        btFuncionarios.setText("Funcionários");
        btFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionariosActionPerformed(evt);
            }
        });
        jPanel1.add(btFuncionarios);

        btServicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons8-suporte-32.png"))); // NOI18N
        btServicos.setMnemonic('s');
        btServicos.setText("Servicos");
        btServicos.setPreferredSize(new java.awt.Dimension(129, 41));
        btServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btServicosActionPerformed(evt);
            }
        });
        jPanel1.add(btServicos);

        btRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/relatório01 - 32.png"))); // NOI18N
        btRelatorios.setMnemonic('r');
        btRelatorios.setText("Relatórios");
        btRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(btRelatorios);

        jpBotoes.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, 590, 250));

        getContentPane().add(jpBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 620, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/TelaFrm.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuBar.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        jmCadastros.setText("Cadastros");
        jmCadastros.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        jmiCadastrarPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCadastrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/cliente 01 - 16x16.png"))); // NOI18N
        jmiCadastrarPaciente.setText("Paciente");
        jmiCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarPacienteActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCadastrarPaciente);

        jmiCadastrarMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCadastrarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/Medico 1 - 16x16.png"))); // NOI18N
        jmiCadastrarMedico.setText("Médico");
        jmiCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarMedicoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCadastrarMedico);

        jmiCadastrarFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/Funcionario 01 - 16x16.png"))); // NOI18N
        jmiCadastrarFuncionario.setText("Funcionário");
        jmiCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCadastrarFuncionario);

        menuBar.add(jmCadastros);

        jmConsultas.setText("Consultas");
        jmConsultas.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        jmiAgendarConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiAgendarConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/icons8-consulta-16.png"))); // NOI18N
        jmiAgendarConsultas.setText("Agendar");
        jmiAgendarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgendarConsultasActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiAgendarConsultas);

        jmiListarConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiListarConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/icons8-lista-restrita-16.png"))); // NOI18N
        jmiListarConsultas.setText("Listar Consultas");
        jmiListarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarConsultasActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiListarConsultas);

        jmiRemarcarEditarConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiRemarcarEditarConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/relatorioTrabalho-icon.png"))); // NOI18N
        jmiRemarcarEditarConsultas.setText("Remarcar/Editar");
        jmiRemarcarEditarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRemarcarEditarConsultasActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiRemarcarEditarConsultas);

        menuBar.add(jmConsultas);

        jmRelatórios.setText("Relatórios");
        jmRelatórios.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        jmiRelatorioConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiRelatorioConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/agenda-icon.png"))); // NOI18N
        jmiRelatorioConsultas.setText("Consutas");
        jmRelatórios.add(jmiRelatorioConsultas);

        jmiRelatorioPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiRelatorioPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/icons8-fundo-da-conferência-selecionado-16.png"))); // NOI18N
        jmiRelatorioPacientes.setText("Pacientes");
        jmRelatórios.add(jmiRelatorioPacientes);

        jmiRelatorioMedicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiRelatorioMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/icons8-médico-16.png"))); // NOI18N
        jmiRelatorioMedicos.setText("Médicos");
        jmRelatórios.add(jmiRelatorioMedicos);

        jmiRelatorioFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiRelatorioFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/cliente-icon.png"))); // NOI18N
        jmiRelatorioFuncionarios.setText("Funcionário");
        jmRelatórios.add(jmiRelatorioFuncionarios);

        menuBar.add(jmRelatórios);

        jmConfiguracoes.setText("Configurações");
        jmConfiguracoes.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N

        jmTema.setText("Tema");

        btnGroupTema.add(rbtnClaro);
        rbtnClaro.setText("Claro");
        rbtnClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClaroActionPerformed(evt);
            }
        });
        jmTema.add(rbtnClaro);

        btnGroupTema.add(rbtnEscuro);
        rbtnEscuro.setSelected(true);
        rbtnEscuro.setText("Escuro");
        rbtnEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEscuroActionPerformed(evt);
            }
        });
        jmTema.add(rbtnEscuro);

        jmConfiguracoes.add(jmTema);

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/sair 16x16.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmConfiguracoes.add(jmiSair);

        menuBar.add(jmConfiguracoes);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarPacienteActionPerformed
        gerIG.janelaCadPaciente();
    }//GEN-LAST:event_jmiCadastrarPacienteActionPerformed

    private void jmiCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarMedicoActionPerformed
        gerIG.janelaCadMedico();
    }//GEN-LAST:event_jmiCadastrarMedicoActionPerformed

    private void jmiCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarFuncionarioActionPerformed
        gerIG.janelaCadFuncionario();
    }//GEN-LAST:event_jmiCadastrarFuncionarioActionPerformed

    private void jmiAgendarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgendarConsultasActionPerformed
        gerIG.janelaCadConsulta();
    }//GEN-LAST:event_jmiAgendarConsultasActionPerformed

    private void jmiListarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarConsultasActionPerformed
        gerIG.janelaListaConsulta();
    }//GEN-LAST:event_jmiListarConsultasActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        gerIG.janelaLogin();
        this.dispose();
    }//GEN-LAST:event_jmiSairActionPerformed

    private void btPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacientesActionPerformed
        gerIG.janelaCadPaciente();
    }//GEN-LAST:event_btPacientesActionPerformed

    private void btServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btServicosActionPerformed
        gerIG.janelaCadServico();
    }//GEN-LAST:event_btServicosActionPerformed

    private void btMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedicosActionPerformed
        gerIG.janelaCadMedico();
    }//GEN-LAST:event_btMedicosActionPerformed

    private void btFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionariosActionPerformed
        gerIG.janelaCadFuncionario();
    }//GEN-LAST:event_btFuncionariosActionPerformed

    private void btConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultasActionPerformed
        gerIG.janelaCadConsulta();
    }//GEN-LAST:event_btConsultasActionPerformed

    private void jmiRemarcarEditarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRemarcarEditarConsultasActionPerformed
        gerIG.janelaCadConsulta();
    }//GEN-LAST:event_jmiRemarcarEditarConsultasActionPerformed

    private void rbtnClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClaroActionPerformed
        FlatAnimatedLafChange.showSnapshot();
        FlatLightLaf.setup();
        FlatLaf.updateUI();
        FlatAnimatedLafChange.hideSnapshotWithAnimation();
    }//GEN-LAST:event_rbtnClaroActionPerformed

    private void rbtnEscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEscuroActionPerformed
        FlatAnimatedLafChange.showSnapshot();
        FlatDarkLaf.setup();
        FlatLaf.updateUI();
        FlatAnimatedLafChange.hideSnapshotWithAnimation();
    }//GEN-LAST:event_rbtnEscuroActionPerformed

    private void btRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRelatoriosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultas;
    private javax.swing.JButton btFuncionarios;
    private javax.swing.JButton btMedicos;
    private javax.swing.JButton btPacientes;
    private javax.swing.JButton btRelatorios;
    private javax.swing.JButton btServicos;
    private javax.swing.ButtonGroup btnGroupTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmConfiguracoes;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmRelatórios;
    private javax.swing.JMenu jmTema;
    private javax.swing.JMenuItem jmiAgendarConsultas;
    private javax.swing.JMenuItem jmiCadastrarFuncionario;
    private javax.swing.JMenuItem jmiCadastrarMedico;
    private javax.swing.JMenuItem jmiCadastrarPaciente;
    private javax.swing.JMenuItem jmiListarConsultas;
    private javax.swing.JMenuItem jmiRelatorioConsultas;
    private javax.swing.JMenuItem jmiRelatorioFuncionarios;
    private javax.swing.JMenuItem jmiRelatorioMedicos;
    private javax.swing.JMenuItem jmiRelatorioPacientes;
    private javax.swing.JMenuItem jmiRemarcarEditarConsultas;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JRadioButtonMenuItem rbtnClaro;
    private javax.swing.JRadioButtonMenuItem rbtnEscuro;
    // End of variables declaration//GEN-END:variables
}
