/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerView;
import control.UtilCPF;
import control.UtilGeral;
import domain.Medico;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/**
 *
 * @author Usuario
 */
public class DlgPesqMedico extends javax.swing.JDialog {
private ControllerView gerIG;
    private Medico medico;

    public DlgPesqMedico(java.awt.Frame parent, boolean modal, ControllerView gerIG) {
        super(parent, modal);
        initComponents();
        this.gerIG = gerIG;
        medico = null;
        
              
    }
    
    public Medico getMedico() {
        return medico;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesq = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        cmbOpcao = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        btListarTodos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPesquisar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 320, 40));

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 50));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 80, 40));

        btnRelatorios.setText("Relatório");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 120, 50));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, 50));

        cmbOpcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "CPF", "E-mail", "Telefone", "CRM", "ID" }));
        getContentPane().add(cmbOpcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 40));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 110, 50));

        btListarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/icons/icons8-multidão-24.png"))); // NOI18N
        btListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(btListarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 40, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Médicos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        txtPesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "E-MAIL", "TELEFONE", "CRM", "ESPECIALIZACAO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(txtPesquisar);

        jPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 590, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/imgs/TelaPaciente.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            gerIG.carregarTabela(txtPesquisar, Medico.class);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar médicos " + ex.getMessage() );
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed

        int linha = txtPesquisar.getSelectedRow();
        if ( linha >= 0 ) {
            medico = (Medico) txtPesquisar.getValueAt(linha, 1);
        }
        else {
            JOptionPane.showMessageDialog(this,"Selecione uma linha.", "Pesquisar Médico", JOptionPane.ERROR_MESSAGE  );
        }

        this.setVisible(false);
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if(validarPesquisa()){
            try {
                List<Medico> lista = gerIG.getGerDominio().pesquisarMedico(txtPesq.getText(), cmbOpcao.getSelectedIndex());

                // APAGA as linhas da tabela
                ( (DefaultTableModel) txtPesquisar.getModel() ).setNumRows(0);

                for (Medico cli : lista ) {
                    // ADICIONAR LINHA NA TABELA        
                    ( (DefaultTableModel) txtPesquisar.getModel() ).addRow( cli.toArray() );                
                }
            } catch (HibernateException  ex) {
                JOptionPane.showMessageDialog(this, ex, "ERRO ao PESQUISAR Médico", JOptionPane.ERROR_MESSAGE  );
            } 
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private boolean validarPesquisa(){
        String msgErro = "";
        if(txtPesq.getText().isEmpty()){
            msgErro += "Insira um valor!\n";
        }
        
        if(cmbOpcao.getSelectedIndex() == 4 && !UtilGeral.isInteger(txtPesq.getText())){
            msgErro += "ID invalido!\n";
        }
        
        if(cmbOpcao.getSelectedIndex() == 5 && !UtilGeral.isInteger(txtPesq.getText())){
            msgErro += "ID invalido!\n";
        }
        
        if(cmbOpcao.getSelectedIndex() == 3 && !UtilGeral.validarTelefone(txtPesq.getText())){
            msgErro += "ID invalido!\n";
        }
        
        if(cmbOpcao.getSelectedIndex() == 1 && !UtilCPF.validarCPF(txtPesq.getText())){
            msgErro += "CPF Invalido \n";
        }
        
        if(msgErro.isEmpty()){
            return true;
        }else{
            JOptionPane.showMessageDialog(this, msgErro, "Verifique os campos e tente novamente", JOptionPane.ERROR_MESSAGE);
            return false; 
        }
    }
    
    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        medico = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarTodosActionPerformed

        formComponentShown(null);
        //lista todos que estão no banco
    }//GEN-LAST:event_btListarTodosActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListarTodos;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox cmbOpcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtPesq;
    private javax.swing.JTable txtPesquisar;
    // End of variables declaration//GEN-END:variables

    
}
